### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'custom_plugin_paths'

### ISSUE THREAD

**Issue by holyender** [Yelp/detect-secrets-server#62]
please help with running using this project.
```
detect-secrets-server add git@github.com:yelp/detect-secrets
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/detect-secrets-server", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets_server/__main__.py", line 22, in main
    args = parse_args(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets_server/__main__.py", line 12, in parse_args
    return ServerParserBuilder().parse_args(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets_server/core/usage/parser.py", line 52, in parse_args
    AddOptions.consolidate_args(output)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets_server/core/usage/add.py", line 123, in consolidate_args
    PluginOptions.consolidate_args(args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/detect_secrets/core/usage.py", line 452, in consolidate_args
    for plugin in get_all_plugin_descriptors(args.custom_plugin_paths):
AttributeError: 'Namespace' object has no attribute 'custom_plugin_paths'

```
Im able to install but unable to run any scans.

**Comment by KevinHock** [comment]
Whoops,
looks like d-s-s needs to pin d-s at `0.13.1`
https://github.com/Yelp/detect-secrets-server/blob/master/setup.py#L28

Try pip installing d-s 0.13.1 and then you won't have that issue.

As for the long-term fix, I'll look later, hopefully reply within a week  💭

**Comment by KevinHock** [comment]
_didn't reply within a week_
My bad.

**Comment by emexelem** [comment]
I'm having the same issue (using virtualenv), and installing detect-secret does not help
```$ pip install detect-secrets 0.13.1
Requirement already satisfied: detect-secrets in ./venv/lib/python3.6/site-packages (0.14.3)
ERROR: Could not find a version that satisfies the requirement 0.13.1 (from versions: none)
ERROR: No matching distribution found for 0.13.1```

**Comment by jamestenglish** [comment]
@emexelem the command is `pip install detect-secrets==0.13.1`

regardless I still can't get things to work. detect secrets server doesn't seem to return anything when I try to scan a local directory, but detect-secrets does

**Comment by KevinHock** [comment]
See https://github.com/Yelp/detect-secrets-server/issues/31#issuecomment-499649306 @jamestenglish

**Comment by mikkelblanne** [comment]
I had the same issue, pinning detect-secrets at 0.13.1 worked.

But I spent some time trying to figure out what was wrong. This has apparently been the out-of-the-box experience for months now. If the long-term fix isn't going to be available in the short term, consider releasing a temporary bugfix version pinning the dependency.

**Comment by match-markhattarki** [comment]
Please update the install instructions on detect-secrets-server to reflect the fact that you have to pin to a earlier version of detect-secrets
