### ISSUE TITLE
fresh pip install of detect-secrets-server[cron] does not seem to install a working version on centos or debian

### ISSUE THREAD

**Issue by match-markhattarki** [Yelp/detect-secrets-server#74]
I have an older centos box that we have been running detect-secret-server on for over a year. I went to upgrade detect-secrets-sever to the latest, and I could not get it to work. Out of frustration, I went to a mostly clean debian box, and isntalled it as per the instructions. I eventually got the same error that I was getting on the centos box. 

after running:
sudo pip3 install detect-secrets-server[cron]
indfunk@debdock:~$ detect-secrets-server add git@github.com:yelp/detect-secrets
Traceback (most recent call last):
  File "/usr/local/bin/detect-secrets-server", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/detect_secrets_server/__main__.py", line 20, in main
    args = parse_args(argv)
  File "/usr/local/lib/python3.7/dist-packages/detect_secrets_server/__main__.py", line 10, in parse_args
    return ServerParserBuilder().parse_args(argv)
  File "/usr/local/lib/python3.7/dist-packages/detect_secrets_server/core/usage/parser.py", line 50, in parse_args
    AddOptions.consolidate_args(output)
  File "/usr/local/lib/python3.7/dist-packages/detect_secrets_server/core/usage/add.py", line 123, in consolidate_args
    PluginOptions.consolidate_args(args)
  File "/usr/local/lib/python3.7/dist-packages/detect_secrets/core/usage.py", line 452, in consolidate_args
    for plugin in get_all_plugin_descriptors(args.custom_plugin_paths):
AttributeError: 'Namespace' object has no attribute 'custom_plugin_paths'

**Comment by nick-hunter** [comment]
Have you seen https://github.com/Yelp/detect-secrets-server/issues/62?

**Comment by match-markhattarki** [comment]
yes. Please update the install documentation to reflect the fact that you must pin to an earlier version of detect-secrets.
